# Generated by Django 4.2.6 on 2023-11-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0018_summary_remove_appointment_customerid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
