# Generated by Django 4.2.6 on 2023-11-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0021_remove_payment_packageid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bloger.servicepack'),
            preserve_default=False,
        ),
    ]
