# Generated by Django 4.2.6 on 2023-11-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0022_payment_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Package',
            new_name='PackageID',
        ),
    ]
