# Generated by Django 4.2.6 on 2023-11-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0023_rename_package_payment_packageid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='PackageID',
            new_name='Name',
        ),
    ]
