# Generated by Django 4.2.6 on 2023-11-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0024_rename_packageid_payment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Name',
            new_name='PackageID',
        ),
    ]
