# Generated by Django 4.2.6 on 2023-10-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web2', '0002_equipmentcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={},
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='category_description',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
