# Generated by Django 4.2.6 on 2023-10-31 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web2', '0003_alter_equipmentcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Category_Id', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EquipmentCategory.model'))),
                ('product_Name', models.CharField(max_length=30)),
                ('Unit_Price', models.IntegerField()),
                ('Sale_Price', models.IntegerField()),
                ('Available_Stock', models.IntegerField()),
                ('Unit_Measure', models.CharField(max_length=4)),
                ('Date_Updated', models.DateField()),
            ],
        ),
    ]
