# Generated by Django 4.2.6 on 2023-10-31 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web2', '0004_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
