# Generated by Django 4.2.6 on 2023-10-31 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web2', '0005_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('unit_price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('Available_stock', models.IntegerField()),
                ('Transaction_amount', models.IntegerField()),
                ('Transaction_date', models.DateField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web2.equipmentcategory')),
            ],
        ),
    ]
