# Generated by Django 4.2.6 on 2023-10-31 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web2', '0006_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('Transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('Transaction_Type', models.CharField(max_length=20)),
                ('Stock_type', models.CharField(max_length=20)),
                ('Transaction_amount', models.IntegerField()),
                ('Transaction_date', models.DateField()),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web2.products')),
            ],
        ),
    ]
