# Generated by Django 4.2.6 on 2023-10-31 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web2', '0007_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Available_stock',
            new_name='available_stock',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Transaction_date',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Transaction_amount',
            new_name='unit_measure',
        ),
    ]
